blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>', views.post_detail, name='post_detail'),
    path('new', views.new_post, name='new_post'),
    path('<int:post_id>/edit', views.edit_post, name='edit_post'),
    path('<int:post_id>/delete', views.delete_post, name='delete_post'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=200)
    text = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text']

blog/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm
from django.contrib.auth.models import User
import datetime

# Create your views here.
def post_list(request):
    posts = Post.objects.order_by('-published_date')
    context = {
        'posts' : posts
    }
    return render(request, 'blog/post_list.html', context)

def post_detail(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        'post' : post
    }
    return render(request, 'blog/post_detail.html', context)

def new_post(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = User.objects.all()[0]
            post.published_date = datetime.datetime.now()
            post.save()
            return redirect('blog:post_detail', post_id=post.id)
   # try changing the else statement to another if statement.
   # check group challenge
    else:
        form = PostForm()
        context = {
        'form' : form,
        'type_of_request': 'New',
    }
    return render(request, 'blog/post_form.html', context)

def edit_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.published_date = datetime.datetime.now()
            post.save()
            return redirect('blog:post_detail', post_id=post.id)
    else:
        form = PostForm(instance=post)
        context = {
            'form' : form,
            'type_of_request' : 'Edit',
        }
        return render(request, 'blog/post_form.html', context)

def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    context = {
        'post': post
    }
    if request.method =='POST':
        post.delete()
        return redirect('blog:post_list')
    return render(request, 'blog/confirm_delete.html', context)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet"> 
    <title>Blog Posts</title>
</head>
<body>
    <div class="page-header">
        <a href="{% url 'blog:new_post' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
        <h1><a href="{% url 'blog:post_list' %}">My Blog</a></h1>
    </div>

    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %} 
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

blog/templates/blog/confirm_delete.html
{% extends 'blog/base.html' %}

{% block content %} 
    <form method="POST" class="post-form">
        {% csrf_token %} 
        <fieldset class="form-group">
            <legend class="'border-bottom mb-4">Delete Post</legend>
            <h2>Are you sure you want to delete the post "{{ post.title }}"?</h2>
        </fieldset>
        <br>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit" formmethod="post">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'blog:post_detail' post.id %}">Cancel</a>
        </div>
    </form>
{% endblock %} 

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %} 

{% block content %} 
    <div class="post">
        <!-- {% if post.published_date %}  -->
        <div class="date">
            {{ post.published_date }}
        </div>
        <!-- {% endif %}  -->
        <a class="btn btn-secondary" href="{% url 'blog:edit_post' post.id %}"><span class="glyphicon glyphicon-pencil">Edit Post</span></a>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text | linebreaksbr }}</p>
        <br>
        <a href="{% url 'blog:delete_post' post.id %}"}>Delete This Post</a>
    </div>
{% endblock %} 

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}

{% block content %} 
    <h2>{{ type_of_request }} Post</h2>
    <form method="POST" class="post-form">
        {% csrf_token %} 
        {{ form.as_p }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %} 

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %} 

{% block content %} 
    {% for post in posts %} 
        <div class="post">
            <div class="date">
                <p>published: {{ post.published_date }}</p>
            </div>
            <h2><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h2>
            <p>{{ post.text | linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}
</body>
</html>